version: '3'
services:
    redis:
        image: redis:alpine
        ports:
            - 6379:6379
    database:
        image: 'postgres:latest'
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=notifications
        volumes:
            - ./database-volume:/var/lib/postgresql/data
